#!/bin/bash

###################
# Starts tests with karma test suite
#
# Arguments:
#   (Optional) --single-run Enables single-run mode on karma
#
# Returns:
#   Test results generated by karma test suite
###################

BASE_DIR=`dirname $0`

echo ""
echo "Starting Karma Server (http://karma-runner.github.io)"
echo "-------------------------------------------------------------------"

if [ ! -z $1 ] ; then
    $BASE_DIR/../../node_modules/karma/bin/karma start $BASE_DIR/../config/karma.conf.js $* $1
else
    $BASE_DIR/../../node_modules/karma/bin/karma start $BASE_DIR/../config/karma.conf.js $*
fi
